#!/usr/bin/env python3
"""Generate a complete `fm` CLI reference from its ArgumentParser help tree.

`fm` is a Swift ArgumentParser app. The hidden `--experimental-dump-help` flag
emits the entire command/subcommand/option tree as JSON in a single call, so we
never have to recursively scrape the ANSI-colored `--help` text.

Usage:
    tools/gen-fm-docs.py                 # writes docs/fm-reference.md
    tools/gen-fm-docs.py --fm /usr/bin/fm --outdir docs
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path


def dump_help(fm_bin: str) -> dict:
    out = subprocess.run(
        [fm_bin, "--experimental-dump-help"],
        capture_output=True, text=True, check=True,
    ).stdout
    return json.loads(out)["command"]


def option_label(a: dict) -> str:
    names = a.get("names", [])
    kind = a.get("kind", "")
    vn = a.get("valueName", "")
    if kind == "positional":
        return f"<{vn}>"
    def fmt(n):
        return ("--" if n["kind"] == "long" else "-") + n["name"]
    label = ", ".join(fmt(n) for n in names)
    if kind == "option":
        label += f" <{vn}>"
    return label


def iter_commands(cmd: dict, path=None):
    path = path or []
    yield " ".join(path + [cmd["commandName"]]), cmd
    for sub in cmd.get("subcommands", []):
        yield from iter_commands(sub, path + [cmd["commandName"]])


def render_md(root: dict) -> str:
    out = ["# `fm` — Apple Foundation Models CLI: Complete Reference\n",
           "_Auto-generated by `tools/gen-fm-docs.py` from "
           "`fm --experimental-dump-help`. Do not edit by hand._\n"]
    for name, cmd in iter_commands(root):
        out.append(f"\n## `{name}`\n")
        if cmd.get("abstract"):
            out.append(cmd["abstract"] + "\n")
        if cmd.get("discussion"):
            out.append("\n```\n" + cmd["discussion"].rstrip() + "\n```\n")
        args = [a for a in cmd.get("arguments", []) if a.get("shouldDisplay", True)]
        if args:
            out.append("\n| Option | Description |\n|---|---|")
            for a in args:
                dv = a.get("defaultValue")
                extra = f" _(default: `{dv}`)_" if dv else ""
                out.append(f"| `{option_label(a)}` | {a.get('abstract','')}{extra} |")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fm", default="/usr/bin/fm", help="path to the fm binary")
    ap.add_argument("--outdir", default="docs", help="output directory")
    args = ap.parse_args()

    root = dump_help(args.fm)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    md_path = outdir / "fm-reference.md"
    md_path.write_text(render_md(root))
    print(f"wrote {md_path}")


if __name__ == "__main__":
    sys.exit(main())
